import time
import logging
import traceback
import asyncio
from datetime import datetime

# Import your core modules
from sensory_core import run_sensory_core
from reasoning_engine import run_causal_simulation
from response_engine import execute_geo_mission

# 1. Setup Logging - This is your 'Black Box' recorder
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - AETHERIUS - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("aetherius_system.log"),
        logging.StreamHandler()
    ]
)

async def aetherius_autonomous_cycle():
    cycle_count = 1
    # Define your interval (e.g., 6 hours = 21600 seconds)
    SLEEP_INTERVAL = 21600 

    logging.info("Sovereign Intelligence Engine Initialized. System: ONLINE.")

    while True:
        start_time = datetime.now()
        logging.info(f"--- STARTING CYCLE #{cycle_count} ---")

        try:
            # PHASE 1: SENSORY (The Eyes)
            logging.info("Phase 1: Engaging Sensory Core...")
            await run_sensory_core() 
            
            # PHASE 2: REASONING (The Brain)
            logging.info("Phase 2: Engaging Reasoning Engine...")
            # We pass the state file generated by the Sensory Core
            run_causal_simulation("market_state.md")
            
            # PHASE 3: RESPONSE (The Hands)
            logging.info("Phase 3: Engaging Response Engine (GEO)...")
            execute_geo_mission("Automated cycle update: Market state refreshed.")

            logging.info(f"CYCLE #{cycle_count} SUCCESSFUL. Duration: {datetime.now() - start_time}")
            cycle_count += 1

        except Exception as e:
            # If any part of the loop fails, we log it and wait before retrying
            logging.error(f"CRITICAL SYSTEM ERROR in Cycle #{cycle_count}: {str(e)}")
            logging.error(traceback.format_exc())
            logging.info("Attempting cooldown before next cycle...")

        # Sleep until the next window
        logging.info(f"System entering hibernation for {SLEEP_INTERVAL/3600} hours.")
        await asyncio.sleep(SLEEP_INTERVAL)

if __name__ == "__main__":
    try:
        asyncio.run(aetherius_autonomous_cycle())
    except KeyboardInterrupt:
        logging.info("Sovereign Shutdown Initiated by User. System: OFFLINE.")